jobs:
  include:
    - os: linux
      dist: bionic
      jdk: openjdk11
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11

language: java

install: unset _JAVA_OPTIONS
script: ./gradlew build --no-daemon --stacktrace

before_cache:
  - rm -f $HOME/.gradle/caches/{modules-2,transforms-1}/*.lock
  - rm -rf $HOME/.gradle/caches/*/{file-changes,fileHashes,plugin-resolution,scripts,scripts-remapped,gradle-script-kotlin}/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
  timeout: 600

notifications:
  email: false
