name: Publish Plugin
on:
  push:
    tags:
      - '[0-9].[0-9].[0-9]-[0-9][0-9][0-9][0-9].[1-3]'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup publish token
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=$HOME/.gradle" >> "$GITHUB_ENV"
          echo "mcdev.deploy.token=${JETBRAINS_TOKEN}" > ~/.gradle/gradle.properties
          echo "mcdev.deploy.channel=testing" >> ~/.gradle/gradle.properties
      - name: Publish plugin
        run: ./gradlew clean publishPlugin --no-daemon --stacktrace
      - name: Get tag name
        id: get_tag
        run: echo ::set-output tag=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: 'Release ${{ steps.get_tag.outputs.tag }}'
          body: '[View all plugin releases here.](https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/stable/)'
          prerelease: false
          draft: false
          files: build/distributions/*.zip
